#! /bin/sh
#! main is invoked via the command line as follows: $ ./xclient-bonus 12345 < client-config-file
#| -*- racket -*-
exec racket -tm "$0" -- ${1+"$@"}
|#
#lang racket

(provide main)

;; ---------------------------------------------------------------------------------------------------
(require "get.rkt")
(require "run-server-client.rkt")
(require Qwirkle/Client/client)

(define (main x)
  (define tag 'xclient)
  (define cc (get jsexpr->client-config tag "ClientConfiguration"))
  (clients (dict-set cc PORT (string->port-number x)) #true))

;; ---------------------------------------------------------------------------------------------------
(module+ test
  (require Qwirkle/Client/client)
  (require json)
  (require rackunit)

  (define tmp-directory "Tmp/")
  (define config-file (~a tmp-directory "config-1.json")))

(module+ test  ;; argument parsing for client configs 
  (delete-directory/files tmp-directory #:must-exist? #false)
  (make-directory tmp-directory)
  
  (define cc default-client-config)

  (with-output-to-file config-file
    #:exists 'replace
    (λ () (write-json (client-config->jsexpr cc) #:indent 4)))

  (define [parse-cc]
    (with-input-from-file config-file (λ () (get jsexpr->client-config 'xclients "ClientConfig"))))
  
  ;; because player names become "" ... 
  (check-equal? (parse-cc) cc))
